plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.google.services)
    alias(libs.plugins.hilt)
    alias(libs.plugins.ksp)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.legacy.kapt)
}

def appVersion = (new File(project.rootDir, 'version.txt')).text.trim()

ext.generateVersionCode = { versionName ->
    def (versionMajor, versionMinor, versionPatch) = versionName.tokenize(".")
    Integer versionCode = versionMajor.toInteger() * 100000000 + versionMinor.toInteger() * 10000 + versionPatch.toInteger()
    logger.info('Version code based on version {}: {}', versionName, versionCode)
    return versionCode
}

android {
    namespace 'com.sample.android.tmdb'
    compileSdk rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "com.sample.android.tmdb"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode generateVersionCode(appVersion)
        versionName appVersion
        buildConfigField "String", "TMDB_API_KEY", "\"${getProperty("local.properties", "tmdb_api_key") ?: System.getenv("TMDB_API_KEY")}\""
        buildConfigField "String", "TMDB_BASE_URL", "\"http://api.themoviedb.org/\""
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    signingConfigs {
        release {
            storeFile file(RELEASE_STORE_FILE)
            storePassword RELEASE_STORE_PASSWORD
            keyAlias RELEASE_KEY_ALIAS
            keyPassword RELEASE_KEY_PASSWORD
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    buildFeatures {
        dataBinding = true
        buildConfig = true
        compose = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Support libraries
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.swiperefreshlayout
    implementation libs.androidx.palette.ktx
    implementation libs.androidx.constraintlayout
    implementation libs.guava

    implementation libs.androidx.fragment.ktx

    // Architecture components
    implementation libs.androidx.paging.runtime
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx

    // Compose
    implementation libs.compose.ui
    implementation libs.compose.material
    debugImplementation libs.compose.ui.tooling
    implementation libs.compose.ui.tooling.preview
    implementation libs.activity.compose
    implementation libs.coil.compose

    // Gson
    implementation libs.gson

    // Retrofit
    implementation libs.retrofit
    implementation libs.retrofit.adapter.rxjava2
    implementation libs.retrofit.converter.gson
    implementation libs.retrofit.mock

    //Android RX
    implementation libs.rxjava
    implementation libs.rxandroid

    // Other
    implementation libs.okhttp.logging.interceptor
    implementation libs.circleimageview
    implementation libs.glide
    ksp libs.glide.compiler

    // Timber
    implementation libs.timber

    // Coroutines
    implementation libs.coroutines.android

    // Dagger
    implementation libs.hilt.android
    ksp libs.hilt.compiler

    // Firebase
    implementation libs.play.core
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.config.ktx
    implementation libs.firebase.analytics.ktx

    // Dependencies for local unit tests
    testImplementation libs.junit
    testImplementation libs.mockito.core

    testImplementation libs.androidx.arch.core.testing
    // mock extension function
    testImplementation libs.mockk
    testImplementation libs.coroutines.test

    // Android Testing Support Library's runner and rules
    androidTestImplementation libs.test.runner
    androidTestImplementation libs.test.rules

    // Espresso UI Testing
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.espresso.contrib
    androidTestImplementation libs.espresso.intents
    androidTestImplementation libs.okhttp3.idling.resource
    implementation libs.espresso.idling.resource
}

def getProperty(String filename, String propName) {
    def propsFile = rootProject.file(filename)
    if (propsFile.exists()) {
        def props = new Properties()
        props.load(new FileInputStream(propsFile))
        if (props[propName] != null) {
            return props[propName]
        } else {
            print("No such property " + propName + " in file " + filename)
        }
    } else {
        print(filename + " does not exist!")
    }
}
